security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user             # 配置登录的账号是user
    password: 123456       # 配置登录的密码是123456
server:
  port: 8888                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756